### ISSUE TITLE
Comando add title="titulo" body="cuerpo"

### ISSUE THREAD

**Issue by arglucho** [arglucho/node-course-udemy#1]
Tengo el mismo codigo que el del final del video, y tambien lo compare con el archivo que deja descargar.

La idea es usar en la terminal: node app.js add title="Un titulo" body="Poner algo de cuerpo"

Y luego tendria que retornar el titulo y luego el cuerpo pero cuando lo hago yo, me aparece que esta faltando el titulo y el cuerpo a pesar de que ya lo pase.

**Comment by br1code** [comment]
Don't forget to include `--` before the name of an argument. Example: `node app.js add --title="Un titulo" --body="Poner algo de cuerpo"`
